### ISSUE TITLE
Resizing large windows in scrollbox.c is slow

### ISSUE THREAD

**Issue by wasamasa** [mobius3/KiWi#13]
[Screencast](https://ptpb.pw/Qsv8.mkv)

edit: Same thing with `drag.c` after resizing its window, then any of the buttons.

**Comment by mobius3** [comment]
Thats because every geometry change in the scrollbox (and the button frames) rerender their texture, which means destroying the old surface and texture, creating a new surface, reblitting all of the tiles and uploading a new texture. In other words, the frame texture is built and then reused in every new widget paint, like a cache. It was not like so, in the past KiWi rendered every tile repeatedly, making having many widgets in the screen very slow.

The proper way, IMO, is to signal (maybe via SetWidgetHint) that the filling tile can be stretched for that particular widget, rewriting the rendering code to consider that. We need to test to see if that is going to be a significant improvement, because the same amount of pixels are going to be blitted in the destination surface. If the user has a tile pattern, then there's not much to do, resizes are going to be slow.

There's also RLE, I guess tileset surfaces are RLE encoded, which makes it even more costlier to blit. I'll check all that when I have the time.

Thanks for the report.

**Comment by wasamasa** [comment]
Thanks, the slowness is gone now.  Although it's still present when resizing one of the buttons, that can be changed by setting a hint for it.
