### ISSUE TITLE
Scrollbox bars are drawn flipped over when dragging beyond x/y position

### ISSUE THREAD

**Issue by wasamasa** [mobius3/KiWi#14]
[Screencast](https://ptpb.pw/1-7k.mkv)

Other than that, I sometimes get "phantom" parts of the buttons displayed which go away on the next resizing cycle, but couldn't record them.

**Comment by mobius3** [comment]
That is funny. I'll check that out when I have the time.

**Comment by wasamasa** [comment]
Hm, not quite gone yet: [Screencast](https://ptpb.pw/9aFs.mkv)

It has improved though as you no longer get it when flipping both sides over, only if you flip either of them.

**Comment by mobius3** [comment]
Yeah, problem is a bit harder to solve than it seems. I'll try to fix it tomorrow. thanks for the screencast.

**Comment by mobius3** [comment]
The scrollbar bug happens because the scrollbar size is fixed, being `TILESIZE * 2` for width or height, depending if it is vertical or horizontal, and because their position is `parentgeometry.{x/y} - TILESEIZE * 3`. The behaviour resulting of this is the problem, obviously is not right, but I haven't yet decided what should be the correct behaviour.

**Comment by wasamasa** [comment]
Thanks, with that change it's gone for me!
