### ISSUE TITLE
Libraries order is important while compiling examples

### ISSUE THREAD

**Issue by sundersb** [mobius3/KiWi#30]
**Good time of the day!**

KiWi examples failed to link with 'undefined references' originated from SDL2main until I reodered libraries for each example in cmake files:

`target_link_libraries(label KiWi ${SDL2_LIBRARIES} ${SDL2MAIN_LIBRARY} ${SDL2_IMAGE_LIBRARIES})`

turned into

`target_link_libraries(label KiWi -lmingw32 ${SDL2MAIN_LIBRARY} ${SDL2_LIBRARIES} ${SDL2_IMAGE_LIBRARIES})`

Seems like the libs should go as mingw32 - SDL2main - SDL2. This was a quick workaround just to test and go on TDM-64 and won't do at large at all. To my shame I'm not much experienced in cmake to suggest a working patch right now - finding SDL on Windows properly is a killer task...

In the rest KiWi compiles easily and with not any single warning.

I notice your project is not much active recently but you should know that I tried many GUI alternatives for SDL. KiWi has advantages before all of them. It is light, does not require many dependencies and builds wonderfully on my whimsy system. Thank you for the job, please don't stop!
👍👍👍

**Comment by mobius3** [comment]
Hi @sundersb! Thank you very much, I'm really glad you found KiWi to be useful and thank you for your report.

I have to update KiWi code to properly link against SDL2, there are some recent changes in the lib (and in newer CMake versions) that might be causing this problem. I'm glad you were able to fix it by yourself and I'll try to provide a fix.

To help me, can you please tell which SDL version you installed on your system, and how? Since you're on windows, if you could point me to the exact link you used to download it would be better. Also, which TDM-64 version are you using? Can you paste the output of `gcc -v`? Lastly, can you tell-me which CMake version are you using?

On KiWi not being much active these days, the reason for that is that I'm working on a successor for it. It is on its very early stages and a lot of its API is to be defined but it is going to be a lot better on a number of areas.

**Comment by sundersb** [comment]
These are my tools:

**SDL2**
Version 2.0.8, downloaded from [official site](https://www.libsdl.org/download-2.0.php) (actual link is https://www.libsdl.org/release/SDL2-devel-2.0.8-mingw.tar.gz). Auxilliary SDL2 libs (image, ttf etc.) I found in [official SDL repository](https://www.libsdl.org/projects/).

**D:\Utils\TDM-GCC-64>gcc -v**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=D:/Utils/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/5.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-5.1.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 5.1.0 (tdm64-1)

Nothing bad could I say about this TDM distribution. Though its' libopengl32 doesn't export glActiveTexture which utterly failed [nanogui-sdl](https://github.com/dalerank/nanogui-sdl) to compile  :P

**CMake**
Version 3.11.0

I will be happy if this information helps you. I hope KiWi successor will stay plain old C and wish you good luck! :)

**Comment by mobius3** [comment]
Oh yeah, plain old C89! Thanks :)
