### ISSUE TITLE
Event Queue will fill up and overflow

### ISSUE THREAD

**Issue by Emersont1** [mobius3/kiwi#41]
I'm not sure how much of an issue this is, but in GUIs that aren't visible, there's no way (without manually changing `KW_gui::evqueuesize`) to set a given GUI to ignore events when it is not being rendered and/or updated, as calling `KW_ProcessEvents` will fire off any buttons if the mouse clicks over where it would be. Ignoring it will fill up the event queue of each GUI until it just overflows and causes a segmentation fault.

Proposed fix/enhancement:
```c
KW_ClearQueue(KW_gui* gui){
  SDL_LockMutex(gui->evqueuelock);
  // 1000 is sufficiently large that it's not going to occur through normal use
  if (gui->evqueuesize > 1000) {
    gui->evqueuesize = 0;
  }
  SDL_UnlockMutex(gui->evqueuelock);
}
```

**Comment by mobius3** [comment]
Thanks for your report.

Maybe we could have the event queue just reset after it is full, what do you think? I mean, if you're not checking 1024 events in a frame, it might event have weird results when you do, so it makes sense to me.

I also believe having a way to clear the event queue is a good idea.

I also think that we might as well take another direction which is to have `KW_HideGUI` or `KW_DisableGUI` or just `KW_DisableGUIEventHandling` so that it would completely ignore events.

We could have all of them. What do you think?

**Comment by Emersont1** [comment]
I like the idea of disabling/hiding the UI as a function. I just posted what i cobbled together yesterday without having to create a massive pull request. I'm more than happy to work on implementing a HideUI function as it will save me having to keep track of every UI instance i create

**Comment by mobius3** [comment]
That's a pull request I'd accept.
